name: pulseguard
version: "1.0.0"
config-version: 2

profile: pulseguard

model-paths: ["models"]
test-paths: ["tests"]

models:
  pulseguard:
    staging:
      +materialized: view
    marts:
      +materialized: table